version: '2.0'
services:

   dockerregistry:
      image: "registry:2"
      container_name: "dockerregistry"
      restart: "always"
      hostname: "dockerregistry"
      environment:
       - "REGISTRY_HTTP_ADDR=0.0.0.0:8443"
       - "REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt"
       - "REGISTRY_HTTP_TLS_KEY=/certs/domain.key"
      ports:
       - "8443:8443"
      volumes:
       - /certs:/certs
      depends_on:
       - "registrator"

   onboardingdb:
      image: "postgres:9.5"
      container_name: "onboardingdb"
      restart: "always"
      hostname: "onboardingdb"
      environment:
       - "POSTGRES_USER=postgres"
       - "POSTGRES_PASSWORD=onap123"
      ports:
       - "5432:5432"
      depends_on:
       - "registrator"
      labels:
       - "SERVICE_5432_NAME=onboardingdb"
       - "SERVICE_5432_CHECK_TCP=true"
       - "SERVICE_5432_CHECK_INTERVAL=15s"
       - "SERVICE_5432_CHECK_INITIAL_STATUS=passing"

   consul:
      image: "consul:0.8.3"
      container_name: "consul"
      restart: "always"
      hostname: "consul"
      ports:
       - "8500:8500"
      environment:
       - "DOCKER_HOST=tcp://${MYIP}:2376"
      volumes:
       - ${PWD}/consul:/opt/consul
      command: "agent -bind 0.0.0.0 -config-file /opt/consul/config.json"
      labels:
       - "SERVICE_8500_NAME=consul"
       - "SERVICE_8500_CHECK_HTTP=/v1/agent/services"
       - "SERVICE_8500_CHECK_INTERVAL=15s"
       - "SERVICE_8500_CHECK_INITIAL_STATUS=passing"

   registrator:
      image: "onapdcae/registrator:v7"
      container_name: "registrator"
      restart: "always"
      hostname: "consul"
      environment:
       - "CONSUL_HOST=consul"
       - "EXTERNAL_IP=${MYIP}"
      volumes:
       - /var/run/docker.sock:/tmp/docker.sock
      depends_on:
       - "consul"

   config-binding-service:
      image: "nexus3.onap.org:10001/onap/org.onap.dcaegen2.platform.configbinding:2.1.5"
      container_name: "config_binding_service"
      restart: "always"
      hostname: "config-binding-service"
      environment:
       - "CONSUL_HOST=consul"
      ports:
       - "10000:10000"
      depends_on:
       - "registrator"
      labels:
       - "SERVICE_10000_NAME=config_binding_service"
       - "SERVICE_10000_CHECK_HTTP=/healthcheck"
       - "SERVICE_10000_CHECK_INTERVAL=15s"
       - "SERVICE_10000_CHECK_INITIAL_STATUS=passing"
       - "SERVICE_443_IGNORE=true"
